/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    MainSideBar: typeof import('./src/components/Main-SideBar.vue')['default']
    MainTopBar: typeof import('./src/components/Main-TopBar.vue')['default']
    MainVideoEleme: typeof import('./src/components/Main-VideoEleme.vue')['default']
    MainWinView: typeof import('./src/components/Main-WinView.vue')['default']
    PlayerAlert: typeof import('./src/components/Player-Alert.vue')['default']
    PlayerContainer: typeof import('./src/components/Player-Container.vue')['default']
    PlayerTopbar: typeof import('./src/components/Player-Topbar.vue')['default']
    PlayerVideoDetail: typeof import('./src/components/Player-VideoDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
